<?php
/**
 * Gabarit « Types - Single » (ex-Oxygen 1615), converti par tools/oxy2php.py le 1er oct. 2026 puis entretenu à la main.
 */
defined('ABSPATH') || exit;
?>
<?php /* En-tête */ ?><section id="section-2-1615" class="ct-section c-bg-light"><div class="ct-section-inner-wrap"><?php /* Rangéee */ ?><div id="div_block-3-1615" class="ct-div-block c-columns-3-2 c-columns-gap-l c-columns-m-1"><?php /* Colonne */ ?><div id="div_block-4-1615" class="ct-div-block c-owl-m c-max-width-640 vertical-align-middle"><h1 id="code_block-5-1615" class="ct-code-block c-tagline c-heading-accent-alt"><?php the_field("entete_sous_titre"); ?></h1><h2 id="code_block-6-1615" class="ct-code-block c-h3 c-heading-dark"><?php the_field("entete_titre"); ?></h2><div id="code_block-7-1615" class="ct-code-block c-text-dark"><?php the_field("entete_contenu"); ?></div><?php if (sx_compare(sx_fn('get_field', 'entete_liens'), 'is_not_blank', '')) : ?><?php /* Liens */ ?><div id="_dynamic_list-43-1615" class="oxy-dynamic-list c-owl-s"><?php $sx_i1 = 0; if (have_rows('field_65b11e0f16470', sx_row_owner('field_65b11e0f16470'))) : while (have_rows('field_65b11e0f16470', sx_row_owner('field_65b11e0f16470'))) : the_row(); $sx_i1++; ?><?php /* Wrapper */ ?><div id="div_block-44-1615-<?php echo (int) $sx_i1; ?>" data-id="div_block-44-1615" class="ct-div-block"><div id="code_block-52-1615-<?php echo (int) $sx_i1; ?>" data-id="code_block-52-1615" class="ct-code-block"><a class="tm-link tm-link-download-accent tm-link-accent" href="<?php the_sub_field("fichier"); ?>" target="_blank">
	<?php the_sub_field("texte"); ?>
</a></div></div><?php endwhile; endif; ?></div><?php endif; ?><?php /* Boutons */ ?><div id="div_block-10-1615" class="ct-div-block c-buttons"><div id="code_block-8-1615" class="ct-code-block"><span class="multi-trigger-soumission c-btn-main c-btn-m c-transition"><?php the_field("lien_soumission_btn_texte", "option"); ?></span></div><div id="code_block-9-1615" class="ct-code-block"><a href="<?php the_field("lien_projets_btn_lien", "option"); ?>" class="c-btn-transparent c-btn-m c-transition"><?php the_field("lien_projets_btn_texte", "option"); ?></a></div></div></div><img id="image-20-1615" alt="" src="<?php echo esc_url((string) get_the_post_thumbnail_url(null, 'full')); ?>" class="ct-image"/></div></div></section><?php /* Contenu */ ?><section id="section-14-1615" class="ct-section"><div class="ct-section-inner-wrap"><?php sx_accordion('-pro-accordion-37-1615', 'accordeons', 'contenu', 'titre', 'contenu', 'Lineariconsicon-arrow-down'); ?></div></section><?php /* Inspirations */ ?><?php sx_oxy_part(1621); ?><?php /* FAQ */ ?><section id="section-38-1615" class="ct-section c-columns-gap-l c-bg-light-alt"><div class="ct-section-inner-wrap"><?php /* Rangée */ ?><div id="div_block-39-1615" class="ct-div-block c-owl-m c-max-width-960 c-center c-center-self"><div id="code_block-40-1615" class="ct-code-block c-tagline c-heading-accent-alt"><?php the_field("bloc_faq_sous_titre", "option"); ?></div><h5 id="code_block-41-1615" class="ct-code-block c-heading-dark c-h3"><?php the_field("bloc_faq_titre", "option"); ?></h5></div><?php sx_accordion('-pro-accordion-42-1615', 'accordeons', 'faq', 'titre', 'contenu', 'Lineariconsicon-arrow-down'); ?></div></section><?php /* CTA */ ?><?php sx_oxy_part(149); ?>
